export const images = {
   userIcon : require('../assets/icons/user.png'),
   passwordIcon : require('../assets/icons/unlock.png'),
   eyeVisibleIcon : require('../assets/icons/visible.png'),
   eyeInvisibleIcon: require('../assets/icons/eye.png'),
   loginImage: require('../assets/images/login_img.jpg'),
   registerImage: require('../assets/images/register.jpg'),
   phoneIcon: require('../assets/icons/phone-call.png'),
   homeIcon : require('../assets/icons/home.png'),
   whislistIcon : require('../assets/icons/package.png'),
   AboutIcon : require('../assets/icons/About.png'),
   LogoutIcon : require('../assets/icons/logout.png'),
   ImageIcon : require('../assets/icons/image.png'),
   CameraIcon : require('../assets/icons/camera2.png'),
   Img1 :require('../assets/images/img1.jpg'),
   Img2 :require('../assets/images/img2.jpg'),
   Img3 :require('../assets/images/img3.jpg'),
   Img4 :require('../assets/images/img4.jpg'),
   Img5 :require('../assets/images/img5.jpg'),
   Img6 :require('../assets/images/img6.jpg'),

}